# Generated by Django 3.1 on 2020-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20200921_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='species',
            field=models.CharField(choices=[('1', 'Select Species'), ('2', 'Orca'), ('3', 'Minke'), ('4', 'Humpback'), ('5', 'Blue'), ('6', 'Sperm'), ('7', 'Beluga'), ('8', 'Gray'), ('9', 'Fin'), ('10', 'Dolphin'), ('11', 'Seal'), ('12', 'Sea Lion'), ('13', 'Sea Otter'), ('14', 'Other'), ('15', 'Unknown')], default='1', max_length=2),
        ),
    ]
